version: '2'
networks:
  lostfound:
services:
  lostfound:
    build: lostfound
    networks:
      - lostfound
    volumes:
      - $PWD/lostfound/webapps:/usr/local/tomcat/webapps
    depends_on:
      - db
    ports:
      - "8080:8080"
  nginx:
    build: nginx
    networks:
      - lostfound
    depends_on:
      - lostfound
    ports:
      - "80:80"
  db:
    image: "mysql:5.7.15"
    networks:
      - lostfound 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: lostfound
      MYSQL_PASSWORD: 1611102
    volumes:
      - $PWD/data:/var/lib/mysql
    ports:
      - "3306:3306"
